#!/bin/sh

echo "commit-msg hook: start"

if ! head -1 "$1" | grep -qE "^(build|chore|ci|docs|fix|feat|perf|refactor|revert|security|style|tests)(\(.+?\))?: .{1,}$"; then
    echo "commit-msg hook: aborting commit - Your commit message doesn't respect conventional commit syntax" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "commit-msg hook: aborting commit - Your commit message is too long" >&2
    exit 1
fi

echo "commit-msg hook: end"
