name: Check commits count

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  count-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Count commits
        id: count_commits
        run: echo "::set-output name=commits_count::$(git rev-list --count HEAD)"

      - name: Check commit count
        id: check_commits_count
        run: |
          if [ "${{ steps.count_commits.outputs.commits_count }}" -gt "1" ]; then
            echo "\033[1;31 [ERROR] There is more than 1 commit found in the PR \033[0m"
            exit 1
          fi
